# Generated by Django 6.0.6 on 2026-07-06 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('publish', 'Publish'), ('reject', 'Reject'), ('submit', 'Submit for Review'), ('login', 'Login'), ('logout', 'Logout'), ('role_change', 'Role Change'), ('view', 'View'), ('export', 'Export')], help_text='Type of action performed', max_length=20)),
                ('content_type', models.CharField(help_text="Model name (e.g., 'Article', 'User', 'Category')", max_length=100)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the object affected')),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the object', max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Dictionary of changes made (field: old_value -> new_value)')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the action (e.g., rejection reason)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='analytics_a_user_id_7c722c_idx'), models.Index(fields=['content_type', 'object_id'], name='analytics_a_content_5653a0_idx'), models.Index(fields=['action', 'timestamp'], name='analytics_a_action_0959ad_idx'), models.Index(fields=['timestamp'], name='analytics_a_timesta_184ff5_idx')],
            },
        ),
    ]
