# Generated by Django 6.0.6 on 2026-07-07 13:28

import analytics.validators.feedback_validator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser device information'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('chat', 'Chat')], max_length=10, validators=[analytics.validators.feedback_validator.validate_content_type])),
                ('object_id', models.PositiveIntegerField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Article rating (1-5 stars)', null=True, validators=[analytics.validators.feedback_validator.validate_rating])),
                ('helpful', models.BooleanField(blank=True, help_text='Was the chat response helpful?', null=True)),
                ('comment', models.TextField(blank=True, validators=[analytics.validators.feedback_validator.validate_comment])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'content_type', 'object_id'], name='analytics_f_user_id_946775_idx'), models.Index(fields=['content_type', 'object_id'], name='analytics_f_content_bc7579_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
