# Generated by Django 6.0.7 on 2026-07-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='conversation_uuid',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
