# Generated by Django 6.0.6 on 2026-07-07 13:36

import analytics.validators.chat_log_validator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_auditlog_user_agent_feedback'),
        ('articles', '0002_alter_article_category_alter_category_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(help_text='Unique identifier for the conversation session', max_length=100, validators=[analytics.validators.chat_log_validator.validate_conversation_id])),
                ('question', models.TextField(help_text="The user's question", validators=[analytics.validators.chat_log_validator.validate_question])),
                ('answer', models.TextField(help_text="The bot's response", validators=[analytics.validators.chat_log_validator.validate_answer])),
                ('was_helpful', models.BooleanField(blank=True, help_text='User feedback on whether the answer was helpful', null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Time taken to generate response (in seconds)', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score of the answer (0-1)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article_ref', models.ForeignKey(blank=True, help_text='Article used to ground the answer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_logs', to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'conversation_id'], name='analytics_c_user_id_a81064_idx'), models.Index(fields=['conversation_id', 'created_at'], name='analytics_c_convers_fa4bdf_idx'), models.Index(fields=['article_ref'], name='analytics_c_article_775e10_idx'), models.Index(fields=['was_helpful'], name='analytics_c_was_hel_811b93_idx')],
            },
        ),
    ]
