# Generated by Django 6.0.7 on 2026-08-03 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_chatlog_conversation_uuid'),
        ('articles', '0009_article_module_article_product_version'),
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatlog',
            name='analytics_c_user_id_a81064_idx',
        ),
        migrations.AddIndex(
            model_name='chatlog',
            index=models.Index(fields=['user', 'conversation_uuid'], name='analytics_c_user_id_5bcd36_idx'),
        ),
    ]
