# Generated by Django 6.0.6 on 2026-07-07 14:34

import analytics.validators.search_log_validator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_chatlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='The search query entered by the user', max_length=500, validators=[analytics.validators.search_log_validator.validate_query])),
                ('result_count', models.PositiveIntegerField(blank=True, help_text='Number of results returned for the query', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='analytics_s_user_id_2cb926_idx'), models.Index(fields=['query'], name='analytics_s_query_86cb43_idx'), models.Index(fields=['created_at'], name='analytics_s_created_269249_idx')],
            },
        ),
    ]
