# Generated by Django 6.0.7 on 2026-08-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_remove_chatlog_analytics_c_user_id_a81064_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='reason',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.TextField(blank=True, help_text='Optional reason for the action (e.g., rejection reason)'),
        ),
    ]
