# Generated by Django 6.0.7 on 2026-08-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_remove_auditlog_reason_alter_auditlog_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True, help_text='Optional reason for the action (e.g., rejection reason)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of changes made (field: old_value -> new_value)'),
        ),
    ]
