# Generated by Django 6.0.7 on 2026-07-22 12:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_articleview'),
        ('articles', '0007_alter_article_article_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleView',
            new_name='ArticleViewLog',
        ),
        migrations.RenameIndex(
            model_name='articleviewlog',
            new_name='analytics_a_article_ca1905_idx',
            old_name='analytics_a_article_38b4ab_idx',
        ),
        migrations.RenameIndex(
            model_name='articleviewlog',
            new_name='analytics_a_timesta_97309c_idx',
            old_name='analytics_a_timesta_ce6291_idx',
        ),
    ]
