# Generated by Django 6.0.7 on 2026-08-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auditlog_reason_alter_auditlog_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='escalate_suggested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('publish', 'Published'), ('reject', 'Rejected'), ('submit', 'Article Submitted'), ('login', 'Login'), ('logout', 'Logout'), ('role_change', 'Role Changed'), ('view', 'Viewed'), ('export', 'Exported')], help_text='Type of action performed', max_length=20),
        ),
    ]
