# Generated by Django 6.0.8 on 2026-08-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_chatlog_escalate_suggested_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('publish', 'Article Published'), ('reject', 'Article Rejected'), ('submit', 'Article Submitted'), ('login', 'Login'), ('logout', 'Logout'), ('role_change', 'Role Changed'), ('view', 'Viewed'), ('export', 'Exported')], help_text='Type of action performed', max_length=20),
        ),
    ]
