# Generated by Django 6.0.7 on 2026-07-24 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_rename_articleview_articleviewlog_and_more'),
        ('articles', '0007_alter_article_article_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='article_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.article'),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='conversation_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='was_helpful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='query',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='result_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
