# Generated by Django 6.0.7 on 2026-07-24 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_alter_chatlog_answer_alter_chatlog_article_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('chat', 'Chat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='helpful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
