# Generated by Django 6.0.8 on 2026-08-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('publish', 'Article Published'), ('reject', 'Article Rejected'), ('submit', 'Article Submitted'), ('login', 'Login'), ('logout', 'Logout'), ('role_change', 'Role Changed'), ('view', 'Viewed'), ('export', 'Exported'), ('archive', 'Archived'), ('restore', 'Restored')], help_text='Type of action performed', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('article_submitted', 'Article Submitted for Review'), ('article_published', 'Article Published'), ('article_rejected', 'Article Rejected'), ('comment_added', 'Comment Added'), ('role_changed', 'Role Changed'), ('article_archived', 'Article Archived'), ('article_restored', 'Article Restored')], max_length=30),
        ),
    ]
