apiVersion: apps/v1
kind: Deployment
metadata:
  name: jeff-hmiskb-be
  namespace: jeff-muna
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jeff-hmiskb-be
  template:
    metadata:
      labels:
        app: jeff-hmiskb-be
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: jeff-hmis-be-container
        image: 024848484634.dkr.ecr.eu-west-1.amazonaws.com/jeff-muna/backend:latest
        envFrom:
        - secretRef:
            name: db-credentials
        env: 
        - name: DB_HOST
          value: "innovation.c3m2emiiu9qh.eu-west-1.rds.amazonaws.com"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: SECRET_KEY
        - name: DEBUG
          value: "1"
        - name: ALLOWED_HOSTS
          value: "jeff-muna.capstone.company.com,localhost,127.0.0.1,192.168.28.241,*.jeff-muna.svc.cluster.local"
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health/
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5