# Generated by Django 6.0.6 on 2026-07-06 10:07

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(default='staff', validators=[users.validators.validate_department]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=20, validators=[users.validators.validate_role]),
        ),
    ]
