# Generated by Django 6.0.7 on 2026-07-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
