# Generated by Django 6.0.7 on 2026-07-17 07:49

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresetotp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, help_text='Cloudinary url', validators=[users.validators.validate_url]),
        ),
    ]
