# Generated by Django 6.0.7 on 2026-08-03 15:56

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(default='staff', max_length=100, validators=[users.validators.validate_department]),
        ),
    ]
