# Generated by Django 6.0.7 on 2026-08-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='faculty',
            new_name='facility',
        ),
    ]
