# Generated by Django 6.0.6 on 2026-07-06 13:30

import articles.validators.category_validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Icon name or emoji, 'fa-user')", max_length=50, validators=[articles.validators.category_validator.validate_icon]),
        ),
    ]
