# Generated by Django 6.0.6 on 2026-07-07 15:11

import articles.validators.media_validator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_category_alter_category_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Original filename', max_length=255, validators=[articles.validators.media_validator.validate_filename])),
                ('url', models.URLField(help_text='Cloudinary URL', max_length=500, validators=[articles.validators.media_validator.validate_url])),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF Document'), ('other', 'Other')], help_text='Media type (image, video, pdf)', max_length=10, validators=[articles.validators.media_validator.validate_media_type])),
                ('public_id', models.CharField(blank=True, help_text='Cloudinary public ID for deletion', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='articles.article')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Media',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', 'type'], name='articles_me_article_d55c26_idx'), models.Index(fields=['uploaded_by'], name='articles_me_uploade_d34b76_idx')],
            },
        ),
    ]
