# Generated by Django 6.0.7 on 2026-07-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='module',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='product_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
