"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

import dj_database_url
from datetime import timedelta

import cloudinary
import cloudinary.uploader
import cloudinary.api
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DEBUG", default=0))

if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver').split(',')


#users
AUTH_USER_MODEL='users.User'
    

#rest framework
REST_FRAMEWORK={
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    # "DEFAULT_PERMISSION_CLASSES":[
    #     "rest_framework.permissons.DjangoModelPernissionsOrAnonReadOnly"
    # ],
    'DEFAULT_AUTHENTICATION_CLASSES':(
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Set JWT as default,,, auth for application
        'rest_framework.authentication.SessionAuthentication' # auth for test
    ),
    "DEFAULT_PAGINATION_CLASS":"rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE":100,
    "DEFAULT_THROTTLE_CLASSES":[
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    # Named rate scopes. Not added to DEFAULT_THROTTLE_CLASSES on purpose —
    # that would throttle every DRF view project-wide, which is a much
    # bigger change than this task's scope. Only views that explicitly set
    # throttle_classes (currently just ChatbotView, see
    # chatbot/security/throttles.py) use these.
    "DEFAULT_THROTTLE_RATES": {
        "chat_anon": "15/min",
        "chat_user": "60/min",
        "anon":'50/min',
        "user":'100/min',
        "request_pwd_reset":"15/min",
        "verify_otp":"15/min",
        "reset_pwd":"15/min"
    },
    "DEFAULT_SCHEMA_CLASS":'drf_spectacular.openapi.AutoSchema',
}

import sys

if 'test' in sys.argv or 'pytest' in sys.argv[0]:
    REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = []
    # REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {}

SIMPLE_JWT={
    'ACCESS_TOKEN_LIFETIME':timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME':timedelta(days=1),
    'SIGNING_KEY':os.environ.get('SIGNING_KEY')
}

SPECTACULAR_SETTINGS={
    'TITLE':'HMIS Knowledge Base API(Taifa Care Help Center)',
    'DESCRIPTION': 'Complete API for the KB platform and Chatbot widget',
    'VERSION': 'V1',
    'SERVE_INCLUDE_SCHEMA':False
}

# Application definition

INSTALLED_APPS = [
    'users.apps.UsersConfig',
    'articles.apps.ArticlesConfig',
    'analytics.apps.AnalyticsConfig',
    'chatbot.apps.ChatbotConfig',
    'drf_spectacular',
    'django_extensions',
    'corsheaders',
    'rest_framework', #djangorestframework
    'rest_framework_simplejwt',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

cloudinary.config(
    cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
    api_key=os.getenv("CLOUDINARY_API_KEY"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET"),
    secure=True
)



# Chatbot LLM provider — see chatbot/services/llm_client.py. Embeddings
# (chatbot/services/embedding_service.py) run locally via sentence-
# transformers and need no API key at all.
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

# Email Configuration SMTP Brevo 
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.getenv('EMAIL_HOST')
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.getenv('BREVO_SMTP_USER')      
# EMAIL_HOST_PASSWORD = os.getenv('BREVO_SMTP_PASSWORD') 

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@hmiskb254.com')

# Email config BREVO API
EMAIL_BACKEND='utils.email_backend.BrevoEmailBackend'
BREVO_API_KEY=os.getenv('BREVO_API_KEY')
EMAIL_SENDER_NAME=os.getenv('EMAIL_SENDER_NAME', 'TaifaCare Help Center')

#frontend
FRONTEND_URL=os.getenv('FRONTEND_URL', 'http://localhost:5173/')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS=[
    'https://taifacarehelpcenter.pages.dev',
    'https://hmis-kb.pages.dev',
    'http://localhost:5173',
    
]

CORS_ALLOW_CREDENTIALS=True

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True
        )
    }
elif os.getenv('DB_HOST'):
    # MySQL/MariaDB fallback (used for the DevOps project)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
            }
        }
    }
elif not os.getenv('DATABASE_URL'):  #for dev
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'hmis_kb_db'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    raise ImproperlyConfigured(
        "No DATABASE_URL or DB_HOST environment variable set."
    )
if os.getenv('DATABASE_URL'):
    DATABASE_URL = os.getenv('DATABASE_URL')
elif os.getenv('DB_HOST'):
    # Build DATABASE_URL from individual env vars (optional)
    DATABASE_URL = f"mysql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT', '3306')}/{os.getenv('DB_NAME')}"
else:
    db = DATABASES['default']
    DATABASE_URL = f"postgresql://{db['USER']}:{db['PASSWORD']}@{db['HOST']}:{db['PORT']}/{db['NAME']}"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Structured logging for the chatbot/RAG pipeline (requests, retrieval,
# LLM latency, provider errors, security events — see
# chatbot/services/rag_pipeline.py and chatbot/security/injection_detection.py).
# No LOGGING config existed anywhere in the project before this — every
# logger.info/warning/exception call in the codebase was going nowhere
# without at least this much configured. Kept intentionally narrow (only
# the chatbot loggers) rather than reconfiguring Django's/other apps'
# logging, which is outside this task's scope.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'structured': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'structured',
        },
    },
    'loggers': {
        'chatbot': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'chatbot.security': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
