# Generated by Django 6.0.7 on 2026-07-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS vector')
    ]
