# Generated by Django 6.0.7 on 2026-07-28 12:41

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0008_alter_article_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS vector'),
        migrations.CreateModel(
            name='ArticleChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, null=True)),
                ('embedding_model', models.CharField(default='BAAI/bge-small-en-v1.5', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='articles.article')),
            ],
            options={
                'ordering': ['article_id', 'chunk_index'],
                'indexes': [models.Index(fields=['article', 'chunk_index'], name='chatbot_art_article_f5a311_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'chunk_index'), name='unique_chunk_per_article')],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='chatbot_con_user_id_0be7ed_idx'), models.Index(fields=['session_key', '-updated_at'], name='chatbot_con_session_0725ad_idx')],
            },
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS article_chunk_embedding_hnsw_idx "
            "ON chatbot_articlechunk USING hnsw (embedding vector_cosine_ops);",
            reverse_sql="DROP INDEX IF EXISTS article_chunk_embedding_hnsw_idx;"
    ),
    ]
