name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.12' 
  DJANGO_SETTINGS_MODULE: app.settings
  ECR_REGISTRY_BE: ${{ secrets.ECR_REGISTRY_BE }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/hmis-kb-backend

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: pgvector/pgvector:pg18 
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('server/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd server
          pip install -r requirements-dev.txt

      - name: Run DB migrations
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/github_actions
        run: |
          cd server
          python manage.py migrate

      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/github_actions
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: 0
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          EMAIL_HOST_USER: ${{ secrets.BREVO_SMTP_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.BREVO_SMTP_PASSWORD }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}
          GROQ_API_KEY: ${{secrets.GROQ_API_KEY}}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          cd server
          pytest -v --tb=short

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()

    steps:
      - name: Check Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push backend image
        working-directory: ./server
        run: |
          docker build -f Dockerfile.backend \
            -t ${{ env.ECR_REGISTRY_BE }}:v1.0.0 \
            -t ${{ env.ECR_REGISTRY_BE }}:${{ github.sha }} \
            -t ${{ env.IMAGE_NAME }}:v2.0.0 \
            -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push --all-tags ${{ env.ECR_REGISTRY_BE }}
          docker push --all-tags ${{ env.IMAGE_NAME }}

      - name: Deploy backend to EKS
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws eks update-kubeconfig --name innovation-lab --region ${{ env.AWS_REGION }}
          kubectl apply -f k8s/deployment-backend.yml -n jeff-muna
          kubectl set image deployment/jeff-hmiskb-be \
            jeff-hmis-be-container=${{ env.ECR_REGISTRY_BE }}:${{ env.IMAGE_TAG }} \
            -n jeff-muna
          kubectl rollout status deployment/jeff-hmiskb-be -n jeff-muna
          kubectl apply -f k8s/service-backend.yml -n jeff-muna